routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\AdminSettingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', [CustomAuthController::class, 'dashboard']); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::resource('adminsetting', AdminSettingController::class);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminSettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use DataTables;
use Auth;
use Illuminate\Support\Facades\Hash;

class AdminSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        
        $data = DB::table('users')
            ->orderBy('id','desc')
            ->paginate(20);
        
        return view('/adminsetting/index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=DB::table('users')
        ->where('users.id', '=', $id)
        ->get();
      
        return view('/adminsetting/edit', compact(['data']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            $lastcreate = date('Y-m-d H:i:s'); // date time update
            // validate ก่อน insert
            $request->validate([
                'name'=>'required',
                'email'=>'required',
                'position'=>'required',
            ]);
            // เพิ่มข้อมูลที่ต้องการ
            $request->request->add([
                'updated_at' => $lastcreate
            ]);
            


            $data = request()->except(['_token','_method']); //นำค่าที่ไม่จำเป็นออก

            //for update data in table
            DB::table('users')->where('id','=', $id)->update([
                'name' => $request->name,
                'email'=> $request->email,
                'position'=> $request->position,
            ]);

            return redirect('/adminsetting')->with('edit','แก้ไขข้อมูลสำเร็จ!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete=DB::table('users')->where('id', '=', $id)->delete();
        return redirect('/adminsetting');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomAuthController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Hash;
use Session;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CustomAuthController extends Controller
{
    public function index()
    {
        return view('auth.login');
    }  
      
    public function customLogin(Request $request)
    {
        $request->validate([
            'email' => 'required',
            'password' => 'required',
        ]);
   
        $credentials = $request->only('email', 'password');
        if (Auth::attempt($credentials)) {

            return redirect()->intended('dashboard')->withSuccess('Signed in');
        }
  
        return redirect("login")->withSuccess('Login details are not valid');
    }

    public function registration()
    {
        return view('auth.registration');
    }
      
    public function customRegistration(Request $request)
    {  
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
        ]);
           
        $data = $request->all();
        $check = $this->create($data);
         
        return redirect("dashboard")->withSuccess('You have signed-in');
    }

    public function create(array $data)
    {
      return User::create([
        'name' => $data['name'],
        'email' => $data['email'],
        'password' => Hash::make($data['password'])
      ]);
    }    
    
    public function dashboard()
    {
        if(Auth::check()){
            return view('dashboard');
        }
  
        return redirect("login")->withSuccess('You are not allowed to access');
    }
    
    public function signOut() {
        Session::flush();
        Auth::logout();
  
        return Redirect('login');
    }
}

resources/views/adminsetting/edit.blade.php
@extends('app')

@section('content')
    <div class="container-fulid">
        <div class="row">
            <div class="col-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-muted">
                            @php
                                $ex_menu = explode("/",Request::server('REQUEST_URI'));
                                echo $ex_menu[1];
                            @endphp
                        </h2>
                        <div class="table-responsive">
                            @foreach ($data as $row)
                                <form class="" action="{{ route('adminsetting.update', $row->id) }}"
                                    method="post" enctype="multipart/form-data">
                                    @csrf @method('PUT')
                                    <input type="hidden" name="id" value="{{ $row->id }}">

                                    <div class="form-group my-2">
                                        <label>ชื่อผู้ใช้ <span style="color:red;">*</span></label>
                                        <input id="name" type="text" class="form-control" name="name" value="{{ $row->name }}" required>
                                    </div>

                                    <div class="form-group my-2">
                                        <label>อีเมล์ <span style="color:red;">*</span></label>
                                        <input id="email" type="email" class="form-control" name="email" value="{{ $row->email }}" readonly>
                                    </div>

                                    <div class="form-group my-2">
                                        <label>ตำแหน่ง <span style="color:red;">*</span></label>
                                        <select name="position" id="position" class="form-control" required>
                                            <option value="">---โปรดระบุ---</option>
                                            <option value="Manager" {{  $row->position === "Manager" ? "selected" : "" }}>Manager</option>
                                            <option value="Developer" {{  $row->position === "Developer" ? "selected" : "" }}>Developer</option>
                                            <option value="Projects Manager" {{  $row->position === "Projects Manager" ? "selected" : "" }}>Projects Manager</option>
                                        </select>
                                    </div>

                                    <div class="text-end">
                                        <button type="submit" class="btn btn-secondary my-2">Submit</button>
                                        <a href="{{ route('adminsetting.index') }}" type="submit" class="btn btn-secondary my-2">Back</a>
                                    </div>
                                    
                                </form>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/adminsetting/index.blade.php
@extends('app')

@section('content')
    @if (session('edit'))
        <div class="alert alert-secondary alert-dismissible fade show" role="alert">
            {{ session('edit') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    <div class="container-fulid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-muted">
                            @php
                                $ex_menu = explode("/",Request::server('REQUEST_URI'));
                                echo $ex_menu[1];
                            @endphp
                        </h2>
                        <div class="row align-items-center">
                                <div class="col-1 col-md-1 d-none d-md-block">
                                    No.
                                </div>
                                
                                <div class="col-md-2 col-5 d-none d-md-block ">
                                    Name
                                </div>
                                <div class="col-md-3 col-6 ">
                                   Email
                                </div>
                                <div class="col-md-2 col-6 ">
                                   Position
                                </div>
                                <div class="col-md-2 col-6 ">
                                    Last Log in
                                </div>
                                <div class="col-md-2 col-4   p-0 ">
                                    Tools
                                </div>
                            </div>
                            <hr>
                        <?php
                        if (isset($_GET['page']) and $_GET['page'] != '1') {
                            $i = ($_GET['page'] - 1) * 20;
                        } else {
                            $i = 0;
                        }
                        ?>
                        @foreach ($data as $key => $row)
                            <div class="row align-items-center my-2">
                                <div class="col-1 col-md-1 d-none d-md-block">
                                    {{ $key + $i + 1 }}
                                </div>
                                
                                <div class="col-md-2 col-5 d-none d-md-block ">
                                    {{ $row->name }}
                                </div>
                                <div class="col-md-3 col-6 ">
                                    {{ $row->email }}
                                </div>
                                <div class="col-md-2 col-6 ">
                                    {{ $row->position }}
                                </div>
                                <div class="col-md-2 col-6 ">
                                    @php
                                        $ex_calendar = explode(" ", $row->email_verified_at );
                                        $ex_date = explode("-", $ex_calendar[0]);
                                        $new_date = $ex_date[2]."/".$ex_date[1]."/".$ex_date[0]." ".$ex_calendar[1];
                                    @endphp
                                    <span class="text-white px-1 py-1" style="background: rgb(2,0,36); background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(21,121,9,1) 0%, rgba(198,255,0,1) 100%); border-radius:8%;">{{ $new_date }}</span>
                                </div>
                                <div class="col-md-2 col-4   p-0 ">
                                    <form action="{{ route('adminsetting.destroy', $row->id) }}" method="post">
                                        <a href="{{ route('adminsetting.edit', $row->id) }}" class="btn btn-sm btn-secondary" title="แก้ไข"> Edit </a>
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-secondary">Delete</button>
                                    </form>
                                </div>
                            </div>

                        @endforeach


                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ $data->links() }}
@endsection

resources/views/adminsetting/password.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fulid">
    <div class="row">
        <div class="col-12">
            <h2 class="text-muted">แก้ไขรหัสผ่าน</h2>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        @foreach ($data as $row)
                        <form class="" action="/adminsetting/update_password/{{$row->id}}}" method="get"
                            enctype="multipart/form-data">
                            @csrf @method('GET')

                            <input type="hidden" name="id" value="{{$row->id}}">
                            <div class="form-group">
                                <label>รหัสผ่าน <span style="color:red;">*</span></label>
                                <input id="password" type="password" class="form-control" name="password" required>
                            </div>
                            <div class="form-group">
                                <label>ยืนยันรหัสผ่าน <span style="color:red;">*</span></label>
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a href="{{route('adminsetting.index')}}" type="submit" class="btn btn-warning">Back</a>
                        </form>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Back-End</title>


    <!-- Scripts -->
    <script src="{{ asset('js/soft-ui-dashboard.js') }}" defer></script>
    <script src="{{ asset('js/soft-ui-dashboard.min.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Edu+TAS+Beginner&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/249768be2c.js" crossorigin="anonymous"></script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


    <!-- Styles -->
    <link href="{{ asset('css/soft-ui-dashboard.css') }}" rel="stylesheet">
    <link href="{{ asset('css/nucleo-icons.css') }}" rel="stylesheet">
    <link href="{{ asset('css/nucleo-svg.css') }}" rel="stylesheet">
    <link href="{{ asset('css/soft-ui-dashboard.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Edu+TAS+Beginner&family=Niramit:wght@200&display=swap');
        body {
            font-family: 'Niramit', sans-serif;
            background: #fafafa;
        }

        p {
            font-family: 'Niramit', sans-serif;
            font-size: 1.1em;
            font-weight: 300;
            line-height: 1.7em;
            color: #999;
        }

        a,
        a:hover,
        a:focus {
            color: inherit;
            text-decoration: none;
            transition: all 0.3s;
        }

        .navbar {
            padding: 15px 10px;
            background: #fff;
            border: none;
            border-radius: 0;
            margin-bottom: 40px;
            box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
        }

        .navbar-btn {
            box-shadow: none;
            outline: none !important;
            border: none;
        }

        .line {
            width: 100%;
            height: 1px;
            border-bottom: 1px dashed #ddd;
            margin: 40px 0;
        }

        /* ---------------------------------------------------
            SIDEBAR STYLE
        ----------------------------------------------------- */

        .wrapper {
            display: flex;
            width: 100%;
            align-items: stretch;
        }

        #sidebar {
            min-width: 300px;
            max-width: 300px;
            background: #97984B;
            color: #fff;
            transition: all 0.3s;
        }

        #sidebar.active {
            margin-left: -300px;
        }

        #sidebar .sidebar-header {
            padding: 20px;
            background: #97984B;
        }

        #sidebar ul.components {
            padding: 20px 0;
            border-bottom: 1px solid #97984B;
        }

        #sidebar ul p {
            color: #fff;
            padding: 10px;
        }

        #sidebar ul li a {
            padding: 10px;
            font-size: 1.1em;
            display: block;
        }

        #sidebar ul li a:hover {
            color: #97984B;
            background: #fff;
        }

        #sidebar ul li.active>a,
        a[aria-expanded="true"] {
            color: #fff;
            background: #97984B;
        }

        a[data-toggle="collapse"] {
            position: relative;
        }

        .dropdown-toggle::after {
            display: block;
            position: absolute;
            top: 50%;
            right: 20px;
            transform: translateY(-50%);
        }

        ul ul a {
            font-size: 0.9em !important;
            padding-left: 30px !important;
            background: #97984B;
        }

        ul.CTAs {
            padding: 20px;
        }

        ul.CTAs a {
            text-align: center;
            font-size: 0.9em !important;
            display: block;
            border-radius: 5px;
            margin-bottom: 5px;
        }

        #content {
            width: 100%;
            padding: 20px;
            min-height: 100vh;
            transition: all 0.3s;
        }

    </style>
    

</head>

<body>
    <div id="app">

        <div class="wrapper">
            <!-- Sidebar  -->
            @guest
            @else
            <nav id="sidebar" style="background-color:#5C5C5C;">
                <div class="sidebar-header" style="background-color:#5C5C5C;">
                    <h3><img src="{{ url('image/logo.png') }}" alt="logo" srcset=""  style="height:50px; width: auto;">&nbsp;QUIZ
                    </h3>
                </div>
                <hr>
                <ul class="list-unstyled components" style="background-color:#5C5C5C;">
                   
                        <li>
                            <a href="{{ url('/dashboard') }}">
                                <i class="fa-solid fa-house"></i> Dashboard
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('adminsetting.index') }}">
                                <i class="fa-solid fa-user"></i> Manage User
                            </a>
                        </li>

                        <li>
                            Account Page
                            <a href="{{ route('signout') }}">
                                <i class="fa-solid fa-right-from-bracket"></i> Logout
                            </a>
                        </li>
                    
                
                    
                </ul>

            </nav>
            @endguest

            <!-- Page Content  -->
            <div id="content">
                @guest
                @else
                <nav class="navbar navbar-expand-lg mb-3" style="opacity: 0.8;">
                    <div class="container-fluid">

                        <div class="col-6">
                            <span style="color:grey;">Page</span><span style="black">{{ Request::server('REQUEST_URI')  }}</span><br>
                            <b>
                                @php
                                    $ex_menu = explode("/",Request::server('REQUEST_URI'));
                                    echo $ex_menu[1];
                                @endphp
                            </b>
                        </div>
                        
                        <ul class="navbar-nav mr-auto" >
                            <i class="fa-solid fa-user"></i>&nbsp;&nbsp;
                            {{ Auth::user()->name }} 
                            &nbsp;&nbsp;<i class="fa-solid fa-caret-down"></i></ul>

                    </div>
                </nav>
                @endguest

                <main>
                    @yield('content')
                </main>
            </div>
        </div>

    </div>

    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous">
    </script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </script>
</body>

</html>

resources/views/dashboard.blade.php
@extends('app')
@section('content')
 
            @guest
                  please Sing in before. 
            @else
                <h2> Welcome, {{ Auth::user()->name }} </h2>
            @endguest


@endsection